# Site settings
title: Conference Name, Year
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write a description for your conference or meeting here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/_confweb" # the subpath of your site, e.g. /blog/
url: "https://website.url" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gpschool
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss

youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: _confweb


  
markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner: 

analytics:
 google:
   tracking_id:  UA-62991754-1 # Google tracking ID if applicable

youtube:
  height: 315
  width: 560

conference:
  draft: true # set to True if the programme is draft only.
  hide_tentative: true
  hosts:

  short_name: CLN # Short name for conference (e.g. AISTATS)
  full_name: Conference Long Name # (e.g. Conference on Artificial Intelligence and Statitics)
  room: Room
  venue: Convention Centre
  location: City, Country
  name: Conference Name
  year: 2017
  month: September
  dates:
  - 2017-09-12
  - 2017-09-13
  chairs:
  - type: Organizers
    people:
    - {given: Jack, family: Jones, url: "http://jackjones.org", institute: Jack Institute}
    - {given: Betty, family: Bloggs, url: "http://bettyblogs.org", institute: Betty Institute}
  sponsors:
  - name: Sponsor Name
    url: Sponsor URL
previous_meeting:
  name:
  url:

map:
  show: False
  mapbox:
    latitude: # latitude of map center
    longitude: # longitude of map center
    map_id: # mapbox id
    access_token: # mapbox access token
    zoom_level: 17
    width: 100%
    height: 500px
